/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var localizedStrings = {
    "Done": "Done",
    "file name label": "Filename",
    "find file": "find file",
    "Full path label": "Select your file...",
    "Hello, World!": "Hello, World!",
    "input feedback": " ",
    "tail_label": "Enter a valid filename",
    "Text": "File name"
};




